### ISSUE TITLE
increase political correctness

### ISSUE THREAD

**Issue by soops** [trommel/rand-paul#1]
you are triggering and offending my beliefs and ruining my allegiance and worship of our dark lord rand paul

please take down this repo or I will have tumblr doxx you for having a different opinion

:wink:

**Comment by trommel** [comment]
what in God's holy name is this

**Comment by soops** [comment]
the future, get with the times its 2015

**Comment by trommel** [comment]
https://www.youtube.com/watch?v=zjNvCBoSyfQ

**Comment by trommel** [comment]
[![its 2015](http://img.youtube.com/vi/zjNvCBoSyfQ/0.jpg)](https://www.youtube.com/watch?v=zjNvCBoSyfQ)

**Comment by soops** [comment]
excuse me... what in *rand paul's* holy name is this?

On Sun, Dec 20, 2015 at 11:33 PM Josh Trommel <notifications@github.com>
wrote:

> [image: its 2015] <https://www.youtube.com/watch?v=zjNvCBoSyfQ>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trommel/rand-paul/issues/1#issuecomment-166223381>.
>
-- 
- Ethan

**Comment by trommel** [comment]
i'm just gonna close this issue and pretend it never happened
